from solution import *

solution = Solution()
answer = solution.reverse(123)
print("Case 1")
print("---")
print("Solution:")
print(321)
print(answer)
print()
answer = solution.reverse(-123)
print("--------------------")
print("Case 2")
print("---")
print("Solution:")
print(-321)
print(answer)
print()
answer = solution.reverse(120)
print("Case 3")
print("---")
print("Solution:")
print(21)
print(answer)

