from solution import *

answer = Solution().myAtoi("42")
print("Case 1")
print("Solution:")
print(42)
print(answer)

print()
print("-----------------")
answer = Solution().myAtoi("-42")
print("Case 2")
print("Solution:")
print(-42)
print(answer)

print()
print("---------------")
answer = Solution().myAtoi("  -42")
print("Case 3")
print("Solution:")
print(-42)
print(answer)

print()
print("----------------")
answer = Solution().myAtoi("1337c0d3")
print("Case 4")
print("Solution:")
print(1337)
print(answer)

print()
print("---------")
answer = Solution().myAtoi("dog1234")
print("Case 5")
print("Solution:")
print(0)
print(answer)
